"use strict";
let exports = {};
// DO NOT EDIT THIS FILE!
// This file was generated by UBI-generators.
// For support contact us on the #ubi slack channel.
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.createCarNowPlayingViewOtherMediaCarthingosEventFactory = void 0;
var SPECIFICATION_ID = "car-now-playing-view-other-media-carthingos";
var APP = "music";
var SPECIFICATION_VERSION = "2.0.0";
var SPECIFICATION_MODE = "default";
var GENERATOR_VERSION = "10.0.2";
function createCarNowPlayingViewOtherMediaCarthingosEventFactory(options) {
    return new CarNowPlayingViewOtherMediaCarthingosEventFactory(options);
}
exports.createCarNowPlayingViewOtherMediaCarthingosEventFactory = createCarNowPlayingViewOtherMediaCarthingosEventFactory;
/**
 * Now Playing View for playing other media than Spotify
 */
var CarNowPlayingViewOtherMediaCarthingosEventFactory = /** @class */ (function () {
    function CarNowPlayingViewOtherMediaCarthingosEventFactory(options) {
        this._path = [{
                name: SPECIFICATION_ID
            }];
        if (options === null || options === void 0 ? void 0 : options.parentAbsoluteLocation) {
            this._parentAbsoluteLocation = options.parentAbsoluteLocation;
        }
    }
    /**
    * @returns A new instance of WindNoiseBannerEventFactory
    */
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.windNoiseBannerFactory = function () {
        return new CarNowPlayingViewOtherMediaCarthingosEventFactory.WindNoiseBannerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of VoiceMutedBannerEventFactory
    */
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.voiceMutedBannerFactory = function () {
        return new CarNowPlayingViewOtherMediaCarthingosEventFactory.VoiceMutedBannerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of PlaySpotifyButtonEventFactory
    */
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.playSpotifyButtonFactory = function () {
        return new CarNowPlayingViewOtherMediaCarthingosEventFactory.PlaySpotifyButtonEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of NowPlayingArtworkEventFactory
    */
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.nowPlayingArtworkFactory = function () {
        return new CarNowPlayingViewOtherMediaCarthingosEventFactory.NowPlayingArtworkEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of ControlButtonsEventFactory
    */
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.controlButtonsFactory = function () {
        return new CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of DialButtonEventFactory
    */
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.dialButtonFactory = function () {
        return new CarNowPlayingViewOtherMediaCarthingosEventFactory.DialButtonEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of BackButtonEventFactory
    */
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.backButtonFactory = function () {
        return new CarNowPlayingViewOtherMediaCarthingosEventFactory.BackButtonEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype._getCurrentLocation = function () {
        return {
            pathNodes: this._path,
            specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
            specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
        };
    };
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.getAbsoluteLocation = function () {
        var _a;
        var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
        return {
            locations: __spreadArrays((parentLocations || []), [
                this._getCurrentLocation()
            ]),
        };
    };
    /**
     * Create impression for CarNowPlayingViewOtherMediaCarthingosEventFactory.
     */
    CarNowPlayingViewOtherMediaCarthingosEventFactory.prototype.impression = function () {
        var data = {
            app: APP,
            generatorVersion: GENERATOR_VERSION,
            specificationVersion: SPECIFICATION_VERSION,
            specificationMode: SPECIFICATION_MODE,
            annotatorConfigurationVersion: '',
            annotatorVersion: '',
            location: this._getCurrentLocation(),
            parentAbsoluteLocation: this._parentAbsoluteLocation
        };
        return data;
    };
    return CarNowPlayingViewOtherMediaCarthingosEventFactory;
}());
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    /**
     * Create WindNoiseBannerEventFactory class with path
     * @param path to this node
     */
    var WindNoiseBannerEventFactory = /** @class */ (function () {
        function WindNoiseBannerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "wind_noise_banner"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of LearnMoreButtonEventFactory
        */
        WindNoiseBannerEventFactory.prototype.learnMoreButtonFactory = function () {
            return new CarNowPlayingViewOtherMediaCarthingosEventFactory.WindNoiseBannerEventFactory.LearnMoreButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of DismissButtonEventFactory
        */
        WindNoiseBannerEventFactory.prototype.dismissButtonFactory = function () {
            return new CarNowPlayingViewOtherMediaCarthingosEventFactory.WindNoiseBannerEventFactory.DismissButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        WindNoiseBannerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        WindNoiseBannerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create impression for WindNoiseBannerEventFactory.
         */
        WindNoiseBannerEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return WindNoiseBannerEventFactory;
    }());
    CarNowPlayingViewOtherMediaCarthingosEventFactory.WindNoiseBannerEventFactory = WindNoiseBannerEventFactory;
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    /**
     * Create VoiceMutedBannerEventFactory class with path
     * @param path to this node
     */
    var VoiceMutedBannerEventFactory = /** @class */ (function () {
        function VoiceMutedBannerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "voice_muted_banner"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of TurnOnMicButtonEventFactory
        */
        VoiceMutedBannerEventFactory.prototype.turnOnMicButtonFactory = function () {
            return new CarNowPlayingViewOtherMediaCarthingosEventFactory.VoiceMutedBannerEventFactory.TurnOnMicButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        VoiceMutedBannerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        VoiceMutedBannerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create impression for VoiceMutedBannerEventFactory.
         */
        VoiceMutedBannerEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return VoiceMutedBannerEventFactory;
    }());
    CarNowPlayingViewOtherMediaCarthingosEventFactory.VoiceMutedBannerEventFactory = VoiceMutedBannerEventFactory;
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    /**
     * Create PlaySpotifyButtonEventFactory class with path
     * @param path to this node
     */
    var PlaySpotifyButtonEventFactory = /** @class */ (function () {
        function PlaySpotifyButtonEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "play_spotify_button"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        PlaySpotifyButtonEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        PlaySpotifyButtonEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for hit ui_navigate action.
       * @param destination the destination field
         */
        PlaySpotifyButtonEventFactory.prototype.hitUiNavigate = function (_a) {
            var destination = _a.destination;
            var data = {
                actionParameterNames: ['destination'],
                actionParameterValues: [destination.toString()],
                actionName: "ui_navigate",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return PlaySpotifyButtonEventFactory;
    }());
    CarNowPlayingViewOtherMediaCarthingosEventFactory.PlaySpotifyButtonEventFactory = PlaySpotifyButtonEventFactory;
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    /**
     * Create NowPlayingArtworkEventFactory class with path
     * @param path to this node
     */
    var NowPlayingArtworkEventFactory = /** @class */ (function () {
        function NowPlayingArtworkEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "now_playing_artwork"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        NowPlayingArtworkEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        NowPlayingArtworkEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for hit pause action.
       * @param item_to_be_paused the item_to_be_paused field
         */
        NowPlayingArtworkEventFactory.prototype.hitPause = function (_a) {
            var itemToBePaused = _a.itemToBePaused;
            var data = {
                actionParameterNames: ['item_to_be_paused'],
                actionParameterValues: [itemToBePaused.toString()],
                actionName: "pause",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for hit resume action.
       * @param item_to_be_resumed the item_to_be_resumed field
         */
        NowPlayingArtworkEventFactory.prototype.hitResume = function (_a) {
            var itemToBeResumed = _a.itemToBeResumed;
            var data = {
                actionParameterNames: ['item_to_be_resumed'],
                actionParameterValues: [itemToBeResumed.toString()],
                actionName: "resume",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return NowPlayingArtworkEventFactory;
    }());
    CarNowPlayingViewOtherMediaCarthingosEventFactory.NowPlayingArtworkEventFactory = NowPlayingArtworkEventFactory;
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    /**
     * Create ControlButtonsEventFactory class with path
     * @param path to this node
     */
    var ControlButtonsEventFactory = /** @class */ (function () {
        function ControlButtonsEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "control_buttons"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of StartVoiceAlexaButtonEventFactory
        */
        ControlButtonsEventFactory.prototype.startVoiceAlexaButtonFactory = function () {
            return new CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory.StartVoiceAlexaButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of SkipPreviousButtonEventFactory
        */
        ControlButtonsEventFactory.prototype.skipPreviousButtonFactory = function () {
            return new CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory.SkipPreviousButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of PlayPauseButtonEventFactory
        */
        ControlButtonsEventFactory.prototype.playPauseButtonFactory = function () {
            return new CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory.PlayPauseButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of SkipNextButtonEventFactory
        */
        ControlButtonsEventFactory.prototype.skipNextButtonFactory = function () {
            return new CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory.SkipNextButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        ControlButtonsEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        ControlButtonsEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        return ControlButtonsEventFactory;
    }());
    CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory = ControlButtonsEventFactory;
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    /**
     * Create DialButtonEventFactory class with path
     * @param path to this node
     */
    var DialButtonEventFactory = /** @class */ (function () {
        function DialButtonEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "dial_button"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        DialButtonEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        DialButtonEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for key_stroke resume action.
       * @param item_to_be_resumed the item_to_be_resumed field
         */
        DialButtonEventFactory.prototype.keyStrokeResume = function (_a) {
            var itemToBeResumed = _a.itemToBeResumed;
            var data = {
                actionParameterNames: ['item_to_be_resumed'],
                actionParameterValues: [itemToBeResumed.toString()],
                actionName: "resume",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "key_stroke",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for key_stroke pause action.
       * @param item_to_be_paused the item_to_be_paused field
         */
        DialButtonEventFactory.prototype.keyStrokePause = function (_a) {
            var itemToBePaused = _a.itemToBePaused;
            var data = {
                actionParameterNames: ['item_to_be_paused'],
                actionParameterValues: [itemToBePaused.toString()],
                actionName: "pause",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "key_stroke",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for rotate increase_volume action.
         */
        DialButtonEventFactory.prototype.rotateIncreaseVolume = function () {
            var data = {
                actionName: "increase_volume",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "rotate",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for rotate decrease_volume action.
         */
        DialButtonEventFactory.prototype.rotateDecreaseVolume = function () {
            var data = {
                actionName: "decrease_volume",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "rotate",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return DialButtonEventFactory;
    }());
    CarNowPlayingViewOtherMediaCarthingosEventFactory.DialButtonEventFactory = DialButtonEventFactory;
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    /**
     * Create BackButtonEventFactory class with path
     * @param path to this node
     */
    var BackButtonEventFactory = /** @class */ (function () {
        function BackButtonEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "back_button"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        BackButtonEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        BackButtonEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for key_stroke ui_navigate action.
       * @param destination the destination field
         */
        BackButtonEventFactory.prototype.keyStrokeUiNavigate = function (_a) {
            var destination = _a.destination;
            var data = {
                actionParameterNames: ['destination'],
                actionParameterValues: [destination.toString()],
                actionName: "ui_navigate",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "key_stroke",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return BackButtonEventFactory;
    }());
    CarNowPlayingViewOtherMediaCarthingosEventFactory.BackButtonEventFactory = BackButtonEventFactory;
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    var WindNoiseBannerEventFactory;
    (function (WindNoiseBannerEventFactory) {
        /**
         * Create LearnMoreButtonEventFactory class with path
         * @param path to this node
         */
        var LearnMoreButtonEventFactory = /** @class */ (function () {
            function LearnMoreButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "learn_more_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            LearnMoreButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            LearnMoreButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_navigate action.
           * @param destination the destination field
             */
            LearnMoreButtonEventFactory.prototype.hitUiNavigate = function (_a) {
                var destination = _a.destination;
                var data = {
                    actionParameterNames: ['destination'],
                    actionParameterValues: [destination.toString()],
                    actionName: "ui_navigate",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return LearnMoreButtonEventFactory;
        }());
        WindNoiseBannerEventFactory.LearnMoreButtonEventFactory = LearnMoreButtonEventFactory;
    })(WindNoiseBannerEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory.WindNoiseBannerEventFactory || (CarNowPlayingViewOtherMediaCarthingosEventFactory.WindNoiseBannerEventFactory = {}));
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    var WindNoiseBannerEventFactory;
    (function (WindNoiseBannerEventFactory) {
        /**
         * Create DismissButtonEventFactory class with path
         * @param path to this node
         */
        var DismissButtonEventFactory = /** @class */ (function () {
            function DismissButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "dismiss_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            DismissButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            DismissButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_hide action.
             */
            DismissButtonEventFactory.prototype.hitUiHide = function () {
                var data = {
                    actionName: "ui_hide",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return DismissButtonEventFactory;
        }());
        WindNoiseBannerEventFactory.DismissButtonEventFactory = DismissButtonEventFactory;
    })(WindNoiseBannerEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory.WindNoiseBannerEventFactory || (CarNowPlayingViewOtherMediaCarthingosEventFactory.WindNoiseBannerEventFactory = {}));
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    var VoiceMutedBannerEventFactory;
    (function (VoiceMutedBannerEventFactory) {
        /**
         * Create TurnOnMicButtonEventFactory class with path
         * @param path to this node
         */
        var TurnOnMicButtonEventFactory = /** @class */ (function () {
            function TurnOnMicButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "turn_on_mic_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            TurnOnMicButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            TurnOnMicButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit setting_enable action.
             */
            TurnOnMicButtonEventFactory.prototype.hitSettingEnable = function () {
                var data = {
                    actionName: "setting_enable",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return TurnOnMicButtonEventFactory;
        }());
        VoiceMutedBannerEventFactory.TurnOnMicButtonEventFactory = TurnOnMicButtonEventFactory;
    })(VoiceMutedBannerEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory.VoiceMutedBannerEventFactory || (CarNowPlayingViewOtherMediaCarthingosEventFactory.VoiceMutedBannerEventFactory = {}));
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    var ControlButtonsEventFactory;
    (function (ControlButtonsEventFactory) {
        /**
         * Create StartVoiceAlexaButtonEventFactory class with path
         * @param path to this node
         */
        var StartVoiceAlexaButtonEventFactory = /** @class */ (function () {
            function StartVoiceAlexaButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "start_voice_alexa_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            StartVoiceAlexaButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            StartVoiceAlexaButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_reveal action.
             */
            StartVoiceAlexaButtonEventFactory.prototype.hitUiReveal = function () {
                var data = {
                    actionName: "ui_reveal",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return StartVoiceAlexaButtonEventFactory;
        }());
        ControlButtonsEventFactory.StartVoiceAlexaButtonEventFactory = StartVoiceAlexaButtonEventFactory;
    })(ControlButtonsEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory || (CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory = {}));
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    var ControlButtonsEventFactory;
    (function (ControlButtonsEventFactory) {
        /**
         * Create SkipPreviousButtonEventFactory class with path
         * @param path to this node
         */
        var SkipPreviousButtonEventFactory = /** @class */ (function () {
            function SkipPreviousButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "skip_previous_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            SkipPreviousButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            SkipPreviousButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit skip_to_previous action.
           * @param item_to_be_skipped the item_to_be_skipped field
           * @param position_ms The position of the playback in milliseconds at the time of the skip
           * @param total_content_ms The length in milliseconds of the track/episode being skipped
             */
            SkipPreviousButtonEventFactory.prototype.hitSkipToPrevious = function (_a) {
                var itemToBeSkipped = _a.itemToBeSkipped, positionMs = _a.positionMs, totalContentMs = _a.totalContentMs;
                var data = {
                    actionParameterNames: ['item_to_be_skipped', 'position_ms', 'total_content_ms'],
                    actionParameterValues: [itemToBeSkipped.toString(), positionMs.toString(), totalContentMs.toString()],
                    actionName: "skip_to_previous",
                    actionVersion: 2,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return SkipPreviousButtonEventFactory;
        }());
        ControlButtonsEventFactory.SkipPreviousButtonEventFactory = SkipPreviousButtonEventFactory;
    })(ControlButtonsEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory || (CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory = {}));
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    var ControlButtonsEventFactory;
    (function (ControlButtonsEventFactory) {
        /**
         * Create PlayPauseButtonEventFactory class with path
         * @param path to this node
         */
        var PlayPauseButtonEventFactory = /** @class */ (function () {
            function PlayPauseButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "play_pause_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            PlayPauseButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            PlayPauseButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit resume action.
           * @param item_to_be_resumed the item_to_be_resumed field
             */
            PlayPauseButtonEventFactory.prototype.hitResume = function (_a) {
                var itemToBeResumed = _a.itemToBeResumed;
                var data = {
                    actionParameterNames: ['item_to_be_resumed'],
                    actionParameterValues: [itemToBeResumed.toString()],
                    actionName: "resume",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            /**
             * Create interaction for hit pause action.
           * @param item_to_be_paused the item_to_be_paused field
             */
            PlayPauseButtonEventFactory.prototype.hitPause = function (_a) {
                var itemToBePaused = _a.itemToBePaused;
                var data = {
                    actionParameterNames: ['item_to_be_paused'],
                    actionParameterValues: [itemToBePaused.toString()],
                    actionName: "pause",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return PlayPauseButtonEventFactory;
        }());
        ControlButtonsEventFactory.PlayPauseButtonEventFactory = PlayPauseButtonEventFactory;
    })(ControlButtonsEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory || (CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory = {}));
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;
(function (CarNowPlayingViewOtherMediaCarthingosEventFactory) {
    var ControlButtonsEventFactory;
    (function (ControlButtonsEventFactory) {
        /**
         * Create SkipNextButtonEventFactory class with path
         * @param path to this node
         */
        var SkipNextButtonEventFactory = /** @class */ (function () {
            function SkipNextButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "skip_next_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            SkipNextButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            SkipNextButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit skip_to_next action.
           * @param item_to_be_skipped the item_to_be_skipped field
           * @param position_ms The position of the playback in milliseconds at the time of the skip
           * @param total_content_ms The length in milliseconds of the track/episode being skipped
             */
            SkipNextButtonEventFactory.prototype.hitSkipToNext = function (_a) {
                var itemToBeSkipped = _a.itemToBeSkipped, positionMs = _a.positionMs, totalContentMs = _a.totalContentMs;
                var data = {
                    actionParameterNames: ['item_to_be_skipped', 'position_ms', 'total_content_ms'],
                    actionParameterValues: [itemToBeSkipped.toString(), positionMs.toString(), totalContentMs.toString()],
                    actionName: "skip_to_next",
                    actionVersion: 2,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return SkipNextButtonEventFactory;
        }());
        ControlButtonsEventFactory.SkipNextButtonEventFactory = SkipNextButtonEventFactory;
    })(ControlButtonsEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory || (CarNowPlayingViewOtherMediaCarthingosEventFactory.ControlButtonsEventFactory = {}));
})(CarNowPlayingViewOtherMediaCarthingosEventFactory = exports.CarNowPlayingViewOtherMediaCarthingosEventFactory || (exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = {}));
exports.CarNowPlayingViewOtherMediaCarthingosEventFactory = CarNowPlayingViewOtherMediaCarthingosEventFactory;

export { CarNowPlayingViewOtherMediaCarthingosEventFactory, createCarNowPlayingViewOtherMediaCarthingosEventFactory };