"use strict";
let exports = {};
// DO NOT EDIT THIS FILE!
// This file was generated by UBI-generators.
// For support contact us on the #ubi slack channel.
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CarNoBluetoothConnectionCarthingosEventFactory = exports.createCarNoBluetoothConnectionCarthingosEventFactory = void 0;
var SPECIFICATION_ID = "car-no-bluetooth-connection-carthingos";
var APP = "music";
var SPECIFICATION_VERSION = "2.0.0";
var SPECIFICATION_MODE = "default";
var GENERATOR_VERSION = "10.0.2";
function createCarNoBluetoothConnectionCarthingosEventFactory(options) {
    return new CarNoBluetoothConnectionCarthingosEventFactory(options);
}
exports.createCarNoBluetoothConnectionCarthingosEventFactory = createCarNoBluetoothConnectionCarthingosEventFactory;
/**
 * A modal shown when no bluetooth connection to a phone is found
 */
var CarNoBluetoothConnectionCarthingosEventFactory = /** @class */ (function () {
    function CarNoBluetoothConnectionCarthingosEventFactory(options) {
        this._path = [{
                name: SPECIFICATION_ID
            }];
        if (options === null || options === void 0 ? void 0 : options.parentAbsoluteLocation) {
            this._parentAbsoluteLocation = options.parentAbsoluteLocation;
        }
    }
    /**
    * @returns A new instance of ShowPairedPhonesButtonEventFactory
    */
    CarNoBluetoothConnectionCarthingosEventFactory.prototype.showPairedPhonesButtonFactory = function () {
        return new CarNoBluetoothConnectionCarthingosEventFactory.ShowPairedPhonesButtonEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    CarNoBluetoothConnectionCarthingosEventFactory.prototype._getCurrentLocation = function () {
        return {
            pathNodes: this._path,
            specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
            specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
        };
    };
    CarNoBluetoothConnectionCarthingosEventFactory.prototype.getAbsoluteLocation = function () {
        var _a;
        var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
        return {
            locations: __spreadArrays((parentLocations || []), [
                this._getCurrentLocation()
            ]),
        };
    };
    /**
     * Create impression for CarNoBluetoothConnectionCarthingosEventFactory.
     */
    CarNoBluetoothConnectionCarthingosEventFactory.prototype.impression = function () {
        var data = {
            app: APP,
            generatorVersion: GENERATOR_VERSION,
            specificationVersion: SPECIFICATION_VERSION,
            specificationMode: SPECIFICATION_MODE,
            annotatorConfigurationVersion: '',
            annotatorVersion: '',
            location: this._getCurrentLocation(),
            parentAbsoluteLocation: this._parentAbsoluteLocation
        };
        return data;
    };
    return CarNoBluetoothConnectionCarthingosEventFactory;
}());
exports.CarNoBluetoothConnectionCarthingosEventFactory = CarNoBluetoothConnectionCarthingosEventFactory;
(function (CarNoBluetoothConnectionCarthingosEventFactory) {
    /**
     * Create ShowPairedPhonesButtonEventFactory class with path
     * @param path to this node
     */
    var ShowPairedPhonesButtonEventFactory = /** @class */ (function () {
        function ShowPairedPhonesButtonEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "show_paired_phones_button"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        ShowPairedPhonesButtonEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        ShowPairedPhonesButtonEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for hit ui_navigate action.
       * @param destination the destination field
         */
        ShowPairedPhonesButtonEventFactory.prototype.hitUiNavigate = function (_a) {
            var destination = _a.destination;
            var data = {
                actionParameterNames: ['destination'],
                actionParameterValues: [destination.toString()],
                actionName: "ui_navigate",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for key_stroke ui_navigate action.
       * @param destination the destination field
         */
        ShowPairedPhonesButtonEventFactory.prototype.keyStrokeUiNavigate = function (_a) {
            var destination = _a.destination;
            var data = {
                actionParameterNames: ['destination'],
                actionParameterValues: [destination.toString()],
                actionName: "ui_navigate",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "key_stroke",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return ShowPairedPhonesButtonEventFactory;
    }());
    CarNoBluetoothConnectionCarthingosEventFactory.ShowPairedPhonesButtonEventFactory = ShowPairedPhonesButtonEventFactory;
})(CarNoBluetoothConnectionCarthingosEventFactory = exports.CarNoBluetoothConnectionCarthingosEventFactory || (exports.CarNoBluetoothConnectionCarthingosEventFactory = {}));
exports.CarNoBluetoothConnectionCarthingosEventFactory = CarNoBluetoothConnectionCarthingosEventFactory;

export { CarNoBluetoothConnectionCarthingosEventFactory, createCarNoBluetoothConnectionCarthingosEventFactory };