export const SHOW_THIS_ARTIST_ACTION = 'SHOW_THIS_ARTIST';
export const SHOW_MY_LIBRARY_ACTION = 'SHOW_MY_LIBRARY';
export const SHOW_MY_PRESETS_ACTION = 'SHOW_MY_PRESETS';
export const SHOW_MY_EPISODES_ACTION = 'SHOW_MY_SAVED_EPISODES';
export const SHOW_MY_NEW_EPISODES_ACTION = 'SHOW_MY_NEW_EPISODES';
export const SHOW_TRACKS_ACTION = 'SHOW_TRACKS';
export const SHOW_THE_QUEUE_ACTION = 'SHOW_THE_QUEUE';
export const SHOW_MY_SONGS_ACTION = 'SHOW_MY_SONGS';
export const SHOW_PODCAST_ACTION = 'SHOW_PODCAST';
export const PLAY_PODCAST_ACTION = 'PLAY_PODCAST';
export const PLAY_SPOTIFY_ACTION = 'PLAY_SPOTIFY';
export const SAVE_TO_COLLECTION_ACTION = 'SAVE_TO_COLLECTION';
export const SAVE_TO_COLLECTION_PODCAST_ACTION = 'SAVE_TO_COLLECTION_PODCAST';
export const SAVE_TO_COLLECTION_EPISODE = 'SAVE_TO_COLLECTION_EPISODE';

const VOICE_CONFIRMATION_ACTIONS = [
  SHOW_THIS_ARTIST_ACTION,
  SHOW_MY_LIBRARY_ACTION,
  SHOW_MY_PRESETS_ACTION,
  SHOW_MY_EPISODES_ACTION,
  SHOW_MY_NEW_EPISODES_ACTION,
  SHOW_TRACKS_ACTION,
  SHOW_THE_QUEUE_ACTION,
  SHOW_MY_SONGS_ACTION,
  SHOW_PODCAST_ACTION,
  PLAY_PODCAST_ACTION,
  PLAY_SPOTIFY_ACTION,
  SAVE_TO_COLLECTION_ACTION,
  SAVE_TO_COLLECTION_PODCAST_ACTION,
  SAVE_TO_COLLECTION_EPISODE,
];

export type VoiceConfirmationAction = typeof VOICE_CONFIRMATION_ACTIONS[number];
