"use strict";
let exports = {};
// DO NOT EDIT THIS FILE!
// This file was generated by UBI-generators.
// For support contact us on the #ubi slack channel.
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CarOnboardingLearnVoiceCarthingosEventFactory = exports.createCarOnboardingLearnVoiceCarthingosEventFactory = void 0;
var SPECIFICATION_ID = "car-onboarding-learn-voice-carthingos";
var APP = "music";
var SPECIFICATION_VERSION = "2.0.0";
var SPECIFICATION_MODE = "default";
var GENERATOR_VERSION = "10.0.2";
function createCarOnboardingLearnVoiceCarthingosEventFactory(options) {
    return new CarOnboardingLearnVoiceCarthingosEventFactory(options);
}
exports.createCarOnboardingLearnVoiceCarthingosEventFactory = createCarOnboardingLearnVoiceCarthingosEventFactory;
/**
 *
 */
var CarOnboardingLearnVoiceCarthingosEventFactory = /** @class */ (function () {
    function CarOnboardingLearnVoiceCarthingosEventFactory(options) {
        this._path = [{
                name: SPECIFICATION_ID
            }];
        if (options === null || options === void 0 ? void 0 : options.parentAbsoluteLocation) {
            this._parentAbsoluteLocation = options.parentAbsoluteLocation;
        }
    }
    /**
    * @returns A new instance of FirstUpContainerEventFactory
    */
    CarOnboardingLearnVoiceCarthingosEventFactory.prototype.firstUpContainerFactory = function () {
        return new CarOnboardingLearnVoiceCarthingosEventFactory.FirstUpContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of TryPlayingPlaylistContainerEventFactory
    */
    CarOnboardingLearnVoiceCarthingosEventFactory.prototype.tryPlayingPlaylistContainerFactory = function () {
        return new CarOnboardingLearnVoiceCarthingosEventFactory.TryPlayingPlaylistContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of TrySkipNextContainerEventFactory
    */
    CarOnboardingLearnVoiceCarthingosEventFactory.prototype.trySkipNextContainerFactory = function () {
        return new CarOnboardingLearnVoiceCarthingosEventFactory.TrySkipNextContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @param id of the ErrorContainerEventFactory
    * @param reason of the ErrorContainerEventFactory
    * @returns A new instance of ErrorContainerEventFactory
    */
    CarOnboardingLearnVoiceCarthingosEventFactory.prototype.errorContainerFactory = function (data) {
        return new CarOnboardingLearnVoiceCarthingosEventFactory.ErrorContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation,
            data: data
        });
    };
    CarOnboardingLearnVoiceCarthingosEventFactory.prototype._getCurrentLocation = function () {
        return {
            pathNodes: this._path,
            specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
            specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
        };
    };
    CarOnboardingLearnVoiceCarthingosEventFactory.prototype.getAbsoluteLocation = function () {
        var _a;
        var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
        return {
            locations: __spreadArrays((parentLocations || []), [
                this._getCurrentLocation()
            ]),
        };
    };
    /**
     * Create impression for CarOnboardingLearnVoiceCarthingosEventFactory.
     */
    CarOnboardingLearnVoiceCarthingosEventFactory.prototype.impression = function () {
        var data = {
            app: APP,
            generatorVersion: GENERATOR_VERSION,
            specificationVersion: SPECIFICATION_VERSION,
            specificationMode: SPECIFICATION_MODE,
            annotatorConfigurationVersion: '',
            annotatorVersion: '',
            location: this._getCurrentLocation(),
            parentAbsoluteLocation: this._parentAbsoluteLocation
        };
        return data;
    };
    return CarOnboardingLearnVoiceCarthingosEventFactory;
}());
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;
(function (CarOnboardingLearnVoiceCarthingosEventFactory) {
    /**
     * Create FirstUpContainerEventFactory class with path
     * @param path to this node
     */
    var FirstUpContainerEventFactory = /** @class */ (function () {
        function FirstUpContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "first_up_container"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of SkipButtonEventFactory
        */
        FirstUpContainerEventFactory.prototype.skipButtonFactory = function () {
            return new CarOnboardingLearnVoiceCarthingosEventFactory.FirstUpContainerEventFactory.SkipButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        FirstUpContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        FirstUpContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create impression for FirstUpContainerEventFactory.
         */
        FirstUpContainerEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return FirstUpContainerEventFactory;
    }());
    CarOnboardingLearnVoiceCarthingosEventFactory.FirstUpContainerEventFactory = FirstUpContainerEventFactory;
})(CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory || (exports.CarOnboardingLearnVoiceCarthingosEventFactory = {}));
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;
(function (CarOnboardingLearnVoiceCarthingosEventFactory) {
    /**
     * Create TryPlayingPlaylistContainerEventFactory class with path
     * @param path to this node
     */
    var TryPlayingPlaylistContainerEventFactory = /** @class */ (function () {
        function TryPlayingPlaylistContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "try_playing_playlist_container"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of SkipButtonEventFactory
        */
        TryPlayingPlaylistContainerEventFactory.prototype.skipButtonFactory = function () {
            return new CarOnboardingLearnVoiceCarthingosEventFactory.TryPlayingPlaylistContainerEventFactory.SkipButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        TryPlayingPlaylistContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        TryPlayingPlaylistContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for speech play action.
       * @param item_to_be_played Item (context, track or episode) the user wants to play
         */
        TryPlayingPlaylistContainerEventFactory.prototype.speechPlay = function (_a) {
            var itemToBePlayed = _a.itemToBePlayed;
            var data = {
                actionParameterNames: ['item_to_be_played'],
                actionParameterValues: [itemToBePlayed.toString()],
                actionName: "play",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "speech",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create impression for TryPlayingPlaylistContainerEventFactory.
         */
        TryPlayingPlaylistContainerEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return TryPlayingPlaylistContainerEventFactory;
    }());
    CarOnboardingLearnVoiceCarthingosEventFactory.TryPlayingPlaylistContainerEventFactory = TryPlayingPlaylistContainerEventFactory;
})(CarOnboardingLearnVoiceCarthingosEventFactory = exports.CarOnboardingLearnVoiceCarthingosEventFactory || (exports.CarOnboardingLearnVoiceCarthingosEventFactory = {}));
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;
(function (CarOnboardingLearnVoiceCarthingosEventFactory) {
    /**
     * Create TrySkipNextContainerEventFactory class with path
     * @param path to this node
     */
    var TrySkipNextContainerEventFactory = /** @class */ (function () {
        function TrySkipNextContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "try_skip_next_container"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of SkipButtonEventFactory
        */
        TrySkipNextContainerEventFactory.prototype.skipButtonFactory = function () {
            return new CarOnboardingLearnVoiceCarthingosEventFactory.TrySkipNextContainerEventFactory.SkipButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        TrySkipNextContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        TrySkipNextContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for speech skip_to_next action.
       * @param item_to_be_skipped the item_to_be_skipped field
       * @param position_ms The position of the playback in milliseconds at the time of the skip
       * @param total_content_ms The length in milliseconds of the track/episode being skipped
         */
        TrySkipNextContainerEventFactory.prototype.speechSkipToNext = function (_a) {
            var itemToBeSkipped = _a.itemToBeSkipped, positionMs = _a.positionMs, totalContentMs = _a.totalContentMs;
            var data = {
                actionParameterNames: ['item_to_be_skipped', 'position_ms', 'total_content_ms'],
                actionParameterValues: [itemToBeSkipped.toString(), positionMs.toString(), totalContentMs.toString()],
                actionName: "skip_to_next",
                actionVersion: 2,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "speech",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create impression for TrySkipNextContainerEventFactory.
         */
        TrySkipNextContainerEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return TrySkipNextContainerEventFactory;
    }());
    CarOnboardingLearnVoiceCarthingosEventFactory.TrySkipNextContainerEventFactory = TrySkipNextContainerEventFactory;
})(CarOnboardingLearnVoiceCarthingosEventFactory = exports.CarOnboardingLearnVoiceCarthingosEventFactory || (exports.CarOnboardingLearnVoiceCarthingosEventFactory = {}));
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;
(function (CarOnboardingLearnVoiceCarthingosEventFactory) {
    /**
     * Create ErrorContainerEventFactory class with path
     * @param path to this node
     */
    var ErrorContainerEventFactory = /** @class */ (function () {
        function ErrorContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat(__assign(__assign({}, data), { name: "error_container" }));
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of NextButtonEventFactory
        */
        ErrorContainerEventFactory.prototype.nextButtonFactory = function () {
            return new CarOnboardingLearnVoiceCarthingosEventFactory.ErrorContainerEventFactory.NextButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        ErrorContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        ErrorContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create impression for ErrorContainerEventFactory.
         */
        ErrorContainerEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return ErrorContainerEventFactory;
    }());
    CarOnboardingLearnVoiceCarthingosEventFactory.ErrorContainerEventFactory = ErrorContainerEventFactory;
})(CarOnboardingLearnVoiceCarthingosEventFactory = exports.CarOnboardingLearnVoiceCarthingosEventFactory || (exports.CarOnboardingLearnVoiceCarthingosEventFactory = {}));
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;
(function (CarOnboardingLearnVoiceCarthingosEventFactory) {
    var FirstUpContainerEventFactory;
    (function (FirstUpContainerEventFactory) {
        /**
         * Create SkipButtonEventFactory class with path
         * @param path to this node
         */
        var SkipButtonEventFactory = /** @class */ (function () {
            function SkipButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "skip_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            SkipButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            SkipButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_navigate action.
           * @param destination the destination field
             */
            SkipButtonEventFactory.prototype.hitUiNavigate = function (_a) {
                var destination = _a.destination;
                var data = {
                    actionParameterNames: ['destination'],
                    actionParameterValues: [destination.toString()],
                    actionName: "ui_navigate",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return SkipButtonEventFactory;
        }());
        FirstUpContainerEventFactory.SkipButtonEventFactory = SkipButtonEventFactory;
    })(FirstUpContainerEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory.FirstUpContainerEventFactory || (CarOnboardingLearnVoiceCarthingosEventFactory.FirstUpContainerEventFactory = {}));
})(CarOnboardingLearnVoiceCarthingosEventFactory = exports.CarOnboardingLearnVoiceCarthingosEventFactory || (exports.CarOnboardingLearnVoiceCarthingosEventFactory = {}));
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;
(function (CarOnboardingLearnVoiceCarthingosEventFactory) {
    var TryPlayingPlaylistContainerEventFactory;
    (function (TryPlayingPlaylistContainerEventFactory) {
        /**
         * Create SkipButtonEventFactory class with path
         * @param path to this node
         */
        var SkipButtonEventFactory = /** @class */ (function () {
            function SkipButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "skip_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            SkipButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            SkipButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_navigate action.
           * @param destination the destination field
             */
            SkipButtonEventFactory.prototype.hitUiNavigate = function (_a) {
                var destination = _a.destination;
                var data = {
                    actionParameterNames: ['destination'],
                    actionParameterValues: [destination.toString()],
                    actionName: "ui_navigate",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return SkipButtonEventFactory;
        }());
        TryPlayingPlaylistContainerEventFactory.SkipButtonEventFactory = SkipButtonEventFactory;
    })(TryPlayingPlaylistContainerEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory.TryPlayingPlaylistContainerEventFactory || (CarOnboardingLearnVoiceCarthingosEventFactory.TryPlayingPlaylistContainerEventFactory = {}));
})(CarOnboardingLearnVoiceCarthingosEventFactory = exports.CarOnboardingLearnVoiceCarthingosEventFactory || (exports.CarOnboardingLearnVoiceCarthingosEventFactory = {}));
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;
(function (CarOnboardingLearnVoiceCarthingosEventFactory) {
    var TrySkipNextContainerEventFactory;
    (function (TrySkipNextContainerEventFactory) {
        /**
         * Create SkipButtonEventFactory class with path
         * @param path to this node
         */
        var SkipButtonEventFactory = /** @class */ (function () {
            function SkipButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "skip_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            SkipButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            SkipButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_navigate action.
           * @param destination the destination field
             */
            SkipButtonEventFactory.prototype.hitUiNavigate = function (_a) {
                var destination = _a.destination;
                var data = {
                    actionParameterNames: ['destination'],
                    actionParameterValues: [destination.toString()],
                    actionName: "ui_navigate",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return SkipButtonEventFactory;
        }());
        TrySkipNextContainerEventFactory.SkipButtonEventFactory = SkipButtonEventFactory;
    })(TrySkipNextContainerEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory.TrySkipNextContainerEventFactory || (CarOnboardingLearnVoiceCarthingosEventFactory.TrySkipNextContainerEventFactory = {}));
})(CarOnboardingLearnVoiceCarthingosEventFactory = exports.CarOnboardingLearnVoiceCarthingosEventFactory || (exports.CarOnboardingLearnVoiceCarthingosEventFactory = {}));
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;
(function (CarOnboardingLearnVoiceCarthingosEventFactory) {
    var ErrorContainerEventFactory;
    (function (ErrorContainerEventFactory) {
        /**
         * Create NextButtonEventFactory class with path
         * @param path to this node
         */
        var NextButtonEventFactory = /** @class */ (function () {
            function NextButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "next_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            NextButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            NextButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_navigate action.
           * @param destination the destination field
             */
            NextButtonEventFactory.prototype.hitUiNavigate = function (_a) {
                var destination = _a.destination;
                var data = {
                    actionParameterNames: ['destination'],
                    actionParameterValues: [destination.toString()],
                    actionName: "ui_navigate",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return NextButtonEventFactory;
        }());
        ErrorContainerEventFactory.NextButtonEventFactory = NextButtonEventFactory;
    })(ErrorContainerEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory.ErrorContainerEventFactory || (CarOnboardingLearnVoiceCarthingosEventFactory.ErrorContainerEventFactory = {}));
})(CarOnboardingLearnVoiceCarthingosEventFactory = exports.CarOnboardingLearnVoiceCarthingosEventFactory || (exports.CarOnboardingLearnVoiceCarthingosEventFactory = {}));
exports.CarOnboardingLearnVoiceCarthingosEventFactory = CarOnboardingLearnVoiceCarthingosEventFactory;

export { CarOnboardingLearnVoiceCarthingosEventFactory, createCarOnboardingLearnVoiceCarthingosEventFactory };