/**
 * Generated by `./scripts/prebuild/generate-icons.ts`.
 * Run `yarn generate-icons` to regenerate.
 */
import React from 'react';
import { findClosestGlyphAvailable, Icon } from "../../";
export function IconPlaybackSpeed0Point8x(props) {
  var _props$autoMirror;

  /* prettier-ignore */
  var iconList = [{
    'size': 16,
    'svgContent': '<path d=\'M15.305 10.527l-1.06-1.061-1.97 1.97-1.97-1.97-1.06 1.061 1.97 1.969-1.97 1.97 1.06 1.061 1.97-1.97 1.97 1.97 1.06-1.061-1.97-1.97 1.97-1.969zm-5.917-4.6c0 .742.31 1.312.84 1.763.528.452 1.35.7 2.046.7.696 0 1.56-.248 2.089-.7.529-.451.798-1.021.798-1.763a2.3 2.3 0 00-.9-1.786c.38-.405.591-.94.59-1.495 0-.64-.292-1.226-.766-1.655-.475-.429-1.16-.666-1.8-.666a2.67 2.67 0 00-1.766.666c-.474.429-.8 1.103-.801 1.655a2.186 2.186 0 00.582 1.489 2.3 2.3 0 00-.912 1.789v.003zm2.887-4.1c.613 0 1.076.352 1.076.82 0 .468-.463.82-1.076.82s-1.058-.345-1.058-.82.445-.824 1.058-.824v.004zm0 3.14c.75 0 1.386.44 1.386.961 0 .521-.635.96-1.386.96-.751 0-1.387-.44-1.387-.96s.635-.965 1.387-.965v.004zM3.668.384C1.722.384.56 1.862.56 4.374c0 2.477 1.16 3.957 3.107 3.957 1.946 0 3.106-1.478 3.106-4C6.774 1.857 5.613.38 3.668.38v.004zm0 6.447c-.4 0-1.607 0-1.607-2.494 0-2.453 1.209-2.453 1.607-2.453.398 0 1.606 0 1.606 2.494 0 2.449-1.21 2.45-1.606 2.45v.003zm4.328-.324a.956.956 0 10.679.279.957.957 0 00-.676-.283l-.003.004z\'/>'
  }, {
    'size': 24,
    'svgContent': '<path d=\'M13.832 9.47c0 2.06 1.982 3.737 4.418 3.737s4.418-1.676 4.418-3.737a3.526 3.526 0 00-1.544-2.833 3.318 3.318 0 001.048-2.416c0-.997-.458-1.858-1.18-2.507-.721-.649-1.758-1.008-2.728-1.008-.97 0-2.003.36-2.725 1.008-.721.649-1.183 1.437-1.183 2.507a3.326 3.326 0 001.031 2.4 3.533 3.533 0 00-1.555 2.849zm4.418-6.761c1.1 0 1.923.65 1.923 1.512s-.826 1.513-1.923 1.513-1.893-.636-1.893-1.513c0-.877.865-1.512 1.893-1.512zm0 5.025c1.311 0 2.418.8 2.418 1.736 0 .936-1.107 1.737-2.418 1.737-1.31 0-2.418-.8-2.418-1.737s1.108-1.733 2.418-1.733v-.003zm2.375 7.45l-2.543 2.544-2.543-2.543-1.414 1.414 2.543 2.543-2.543 2.543 1.414 1.414 2.543-2.543 2.543 2.543 1.414-1.414-2.543-2.543 2.543-2.543-1.414-1.414zM5.885.614c-3.03 0-4.77 2.232-4.77 6.184 0 3.9 1.74 6.13 4.77 6.13 3.031 0 4.77-2.231 4.77-6.2 0-3.884-1.739-6.114-4.77-6.114zm0 10.315c-1.838 0-2.77-1.39-2.77-4.19 0-2.738.932-4.125 2.77-4.125s2.77 1.385 2.77 4.19c0 2.734-.932 4.125-2.77 4.125zm6.112-.172a.96.96 0 100 1.92.96.96 0 000-1.92z\'/>'
  }];
  var closestSize = findClosestGlyphAvailable(iconList, props.iconSize || 24);

  var titleTag = function titleTag(title, titleId) {
    return title ? "<title ".concat(titleId ? "id=\"".concat(titleId, "\"") : "", ">").concat(title, "</title>") : "";
  };

  var descTag = function descTag(desc, descId) {
    return desc ? "<desc ".concat(descId ? "id=\"".concat(descId, "\"") : "", ">").concat(desc, "</desc>") : "";
  };

  var autoMirror = (_props$autoMirror = props.autoMirror) !== null && _props$autoMirror !== void 0 ? _props$autoMirror : false;
  return /*#__PURE__*/React.createElement(Icon, Object.assign({}, props, {
    autoMirror: autoMirror,
    viewBox: "0 0 ".concat(closestSize.size, " ").concat(closestSize.size),
    dangerouslySetInnerHTML: {
      __html: "".concat(titleTag(props.title, props.titleId)).concat(descTag(props.desc, props.descId)).concat(closestSize.svgContent)
    }
  }));
}
/**
 * @deprecated The name IconPlaybackSpeed0point8x is deprecated and will be archived soon. Use IconPlaybackSpeed0Point8x (with 'Point' capitalized) instead.
 */

export function IconPlaybackSpeed0point8x(props) {
  return /*#__PURE__*/React.createElement(IconPlaybackSpeed0Point8x, props);
}
/**
 * @deprecated The name Experimental__IconPlaybackSpeed0Point8x is deprecated and will be archived soon. Use IconPlaybackSpeed0Point8x instead.
 */

export function Experimental__IconPlaybackSpeed0Point8x(props) {
  return /*#__PURE__*/React.createElement(IconPlaybackSpeed0Point8x, props);
}