"use strict";
let exports = {};
// DO NOT EDIT THIS FILE!
// This file was generated by UBI-generators.
// For support contact us on the #ubi slack channel.
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CarTrackViewCarthingosEventFactory = exports.createCarTrackViewCarthingosEventFactory = void 0;
var SPECIFICATION_ID = "car-track-view-carthingos";
var APP = "music";
var SPECIFICATION_VERSION = "3.0.0";
var SPECIFICATION_MODE = "default";
var GENERATOR_VERSION = "10.0.2";
function createCarTrackViewCarthingosEventFactory(options) {
    return new CarTrackViewCarthingosEventFactory(options);
}
exports.createCarTrackViewCarthingosEventFactory = createCarTrackViewCarthingosEventFactory;
/**
 * Track View as seen on Car Thing
 */
var CarTrackViewCarthingosEventFactory = /** @class */ (function () {
    function CarTrackViewCarthingosEventFactory(options) {
        this._path = [__assign({ name: SPECIFICATION_ID }, options.data)];
        if (options === null || options === void 0 ? void 0 : options.parentAbsoluteLocation) {
            this._parentAbsoluteLocation = options.parentAbsoluteLocation;
        }
    }
    /**
    * @param position of the DialButtonEventFactory
    * @param uri of the DialButtonEventFactory
    * @returns A new instance of DialButtonEventFactory
    */
    CarTrackViewCarthingosEventFactory.prototype.dialButtonFactory = function (data) {
        return new CarTrackViewCarthingosEventFactory.DialButtonEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation,
            data: data
        });
    };
    /**
    * @returns A new instance of BackButtonEventFactory
    */
    CarTrackViewCarthingosEventFactory.prototype.backButtonFactory = function () {
        return new CarTrackViewCarthingosEventFactory.BackButtonEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @param position of the TrackRowEventFactory
    * @param uri of the TrackRowEventFactory
    * @returns A new instance of TrackRowEventFactory
    */
    CarTrackViewCarthingosEventFactory.prototype.trackRowFactory = function (data) {
        return new CarTrackViewCarthingosEventFactory.TrackRowEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation,
            data: data
        });
    };
    /**
    * @returns A new instance of SaveButtonEventFactory
    */
    CarTrackViewCarthingosEventFactory.prototype.saveButtonFactory = function () {
        return new CarTrackViewCarthingosEventFactory.SaveButtonEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    CarTrackViewCarthingosEventFactory.prototype._getCurrentLocation = function () {
        return {
            pathNodes: this._path,
            specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
            specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
        };
    };
    CarTrackViewCarthingosEventFactory.prototype.getAbsoluteLocation = function () {
        var _a;
        var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
        return {
            locations: __spreadArrays((parentLocations || []), [
                this._getCurrentLocation()
            ]),
        };
    };
    /**
     * Create impression for CarTrackViewCarthingosEventFactory.
     */
    CarTrackViewCarthingosEventFactory.prototype.impression = function () {
        var data = {
            app: APP,
            generatorVersion: GENERATOR_VERSION,
            specificationVersion: SPECIFICATION_VERSION,
            specificationMode: SPECIFICATION_MODE,
            annotatorConfigurationVersion: '',
            annotatorVersion: '',
            location: this._getCurrentLocation(),
            parentAbsoluteLocation: this._parentAbsoluteLocation
        };
        return data;
    };
    return CarTrackViewCarthingosEventFactory;
}());
exports.CarTrackViewCarthingosEventFactory = CarTrackViewCarthingosEventFactory;
(function (CarTrackViewCarthingosEventFactory) {
    /**
     * Create DialButtonEventFactory class with path
     * @param path to this node
     */
    var DialButtonEventFactory = /** @class */ (function () {
        function DialButtonEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat(__assign(__assign({}, data), { name: "dial_button" }));
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        DialButtonEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        DialButtonEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for key_stroke play action.
       * @param item_to_be_played Item (context, track or episode) the user wants to play
         */
        DialButtonEventFactory.prototype.keyStrokePlay = function (_a) {
            var itemToBePlayed = _a.itemToBePlayed;
            var data = {
                actionParameterNames: ['item_to_be_played'],
                actionParameterValues: [itemToBePlayed.toString()],
                actionName: "play",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "key_stroke",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for key_stroke ui_navigate action.
       * @param destination the destination field
         */
        DialButtonEventFactory.prototype.keyStrokeUiNavigate = function (_a) {
            var destination = _a.destination;
            var data = {
                actionParameterNames: ['destination'],
                actionParameterValues: [destination.toString()],
                actionName: "ui_navigate",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "key_stroke",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return DialButtonEventFactory;
    }());
    CarTrackViewCarthingosEventFactory.DialButtonEventFactory = DialButtonEventFactory;
})(CarTrackViewCarthingosEventFactory = exports.CarTrackViewCarthingosEventFactory || (exports.CarTrackViewCarthingosEventFactory = {}));
exports.CarTrackViewCarthingosEventFactory = CarTrackViewCarthingosEventFactory;
(function (CarTrackViewCarthingosEventFactory) {
    /**
     * Create BackButtonEventFactory class with path
     * @param path to this node
     */
    var BackButtonEventFactory = /** @class */ (function () {
        function BackButtonEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "back_button"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        BackButtonEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        BackButtonEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for key_stroke ui_navigate_back action.
         */
        BackButtonEventFactory.prototype.keyStrokeUiNavigateBack = function () {
            var data = {
                actionName: "ui_navigate_back",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "key_stroke",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return BackButtonEventFactory;
    }());
    CarTrackViewCarthingosEventFactory.BackButtonEventFactory = BackButtonEventFactory;
})(CarTrackViewCarthingosEventFactory = exports.CarTrackViewCarthingosEventFactory || (exports.CarTrackViewCarthingosEventFactory = {}));
exports.CarTrackViewCarthingosEventFactory = CarTrackViewCarthingosEventFactory;
(function (CarTrackViewCarthingosEventFactory) {
    /**
     * Create TrackRowEventFactory class with path
     * @param path to this node
     */
    var TrackRowEventFactory = /** @class */ (function () {
        function TrackRowEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat(__assign(__assign({}, data), { name: "track_row" }));
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of AddToQueueButtonEventFactory
        */
        TrackRowEventFactory.prototype.addToQueueButtonFactory = function () {
            return new CarTrackViewCarthingosEventFactory.TrackRowEventFactory.AddToQueueButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        TrackRowEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        TrackRowEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for hit play action.
       * @param item_to_be_played Item (context, track or episode) the user wants to play
         */
        TrackRowEventFactory.prototype.hitPlay = function (_a) {
            var itemToBePlayed = _a.itemToBePlayed;
            var data = {
                actionParameterNames: ['item_to_be_played'],
                actionParameterValues: [itemToBePlayed.toString()],
                actionName: "play",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for hit ui_navigate action.
       * @param destination the destination field
         */
        TrackRowEventFactory.prototype.hitUiNavigate = function (_a) {
            var destination = _a.destination;
            var data = {
                actionParameterNames: ['destination'],
                actionParameterValues: [destination.toString()],
                actionName: "ui_navigate",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for long_hit add_item_to_queue action.
       * @param item_to_add_to_queue the item_to_add_to_queue field
         */
        TrackRowEventFactory.prototype.longHitAddItemToQueue = function (_a) {
            var itemToAddToQueue = _a.itemToAddToQueue;
            var data = {
                actionParameterNames: ['item_to_add_to_queue'],
                actionParameterValues: [itemToAddToQueue.toString()],
                actionName: "add_item_to_queue",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "long_hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create impression for TrackRowEventFactory.
         */
        TrackRowEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return TrackRowEventFactory;
    }());
    CarTrackViewCarthingosEventFactory.TrackRowEventFactory = TrackRowEventFactory;
})(CarTrackViewCarthingosEventFactory = exports.CarTrackViewCarthingosEventFactory || (exports.CarTrackViewCarthingosEventFactory = {}));
exports.CarTrackViewCarthingosEventFactory = CarTrackViewCarthingosEventFactory;
(function (CarTrackViewCarthingosEventFactory) {
    /**
     * Create SaveButtonEventFactory class with path
     * @param path to this node
     */
    var SaveButtonEventFactory = /** @class */ (function () {
        function SaveButtonEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "save_button"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        SaveButtonEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        SaveButtonEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for hit like action.
       * @param item_to_be_liked the item_to_be_liked field
         */
        SaveButtonEventFactory.prototype.hitLike = function (_a) {
            var itemToBeLiked = _a.itemToBeLiked;
            var data = {
                actionParameterNames: ['item_to_be_liked'],
                actionParameterValues: [itemToBeLiked.toString()],
                actionName: "like",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create interaction for hit remove_like action.
       * @param item_no_longer_liked the item_no_longer_liked field
         */
        SaveButtonEventFactory.prototype.hitRemoveLike = function (_a) {
            var itemNoLongerLiked = _a.itemNoLongerLiked;
            var data = {
                actionParameterNames: ['item_no_longer_liked'],
                actionParameterValues: [itemNoLongerLiked.toString()],
                actionName: "remove_like",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return SaveButtonEventFactory;
    }());
    CarTrackViewCarthingosEventFactory.SaveButtonEventFactory = SaveButtonEventFactory;
})(CarTrackViewCarthingosEventFactory = exports.CarTrackViewCarthingosEventFactory || (exports.CarTrackViewCarthingosEventFactory = {}));
exports.CarTrackViewCarthingosEventFactory = CarTrackViewCarthingosEventFactory;
(function (CarTrackViewCarthingosEventFactory) {
    var TrackRowEventFactory;
    (function (TrackRowEventFactory) {
        /**
         * Create AddToQueueButtonEventFactory class with path
         * @param path to this node
         */
        var AddToQueueButtonEventFactory = /** @class */ (function () {
            function AddToQueueButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "add_to_queue_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            AddToQueueButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            AddToQueueButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit add_item_to_queue action.
           * @param item_to_add_to_queue the item_to_add_to_queue field
             */
            AddToQueueButtonEventFactory.prototype.hitAddItemToQueue = function (_a) {
                var itemToAddToQueue = _a.itemToAddToQueue;
                var data = {
                    actionParameterNames: ['item_to_add_to_queue'],
                    actionParameterValues: [itemToAddToQueue.toString()],
                    actionName: "add_item_to_queue",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return AddToQueueButtonEventFactory;
        }());
        TrackRowEventFactory.AddToQueueButtonEventFactory = AddToQueueButtonEventFactory;
    })(TrackRowEventFactory = CarTrackViewCarthingosEventFactory.TrackRowEventFactory || (CarTrackViewCarthingosEventFactory.TrackRowEventFactory = {}));
})(CarTrackViewCarthingosEventFactory = exports.CarTrackViewCarthingosEventFactory || (exports.CarTrackViewCarthingosEventFactory = {}));
exports.CarTrackViewCarthingosEventFactory = CarTrackViewCarthingosEventFactory;

export { CarTrackViewCarthingosEventFactory, createCarTrackViewCarthingosEventFactory };