/**
 * Generated by `./scripts/prebuild/generate-icons.ts`.
 * Run `yarn generate-icons` to regenerate.
 */
import React from 'react';
import { findClosestGlyphAvailable, Icon } from "../../";
export function IconArtist(props) {
  var _props$autoMirror;

  /* prettier-ignore */
  var iconList = [{
    'size': 16,
    'svgContent': '<path d=\'M11.757 2.987A4.356 4.356 0 007.618 0a4.362 4.362 0 00-4.139 2.987 5.474 5.474 0 00-.22 1.894 5.604 5.604 0 001.4 3.312l.125.152a.748.748 0 01-.2 1.128l-2.209 1.275A4.748 4.748 0 000 14.857v1.142h8.734A5.48 5.48 0 018.15 14.5H1.517a3.245 3.245 0 011.6-2.454l2.21-1.275a2.25 2.25 0 00.6-3.386l-.128-.153a4.112 4.112 0 01-1.05-2.44A4.053 4.053 0 014.89 3.47a2.797 2.797 0 011.555-1.713 2.89 2.89 0 013.293.691c.265.296.466.644.589 1.022.12.43.169.876.144 1.322a4.12 4.12 0 01-1.052 2.44l-.127.153a2.239 2.239 0 00-.2 2.58c.338-.45.742-.845 1.2-1.173 0-.162.055-.32.156-.447l.126-.152a5.598 5.598 0 001.4-3.312 5.499 5.499 0 00-.218-1.894zm3.493 3.771a.75.75 0 00-.75.75v3.496h-1a2.502 2.502 0 00-2.31 1.542 2.497 2.497 0 001.822 3.406A2.502 2.502 0 0016 13.502V7.508a.75.75 0 00-.75-.75zm-.75 6.744a.998.998 0 01-1.707.707 1 1 0 01.707-1.706h1v1z\'/>'
  }, {
    'size': 24,
    'svgContent': '<path d=\'M13.363 10.474l-.521.625a2.499 2.499 0 00.67 3.766l.285.164a5.998 5.998 0 011.288-1.565l-.573-.33a.5.5 0 01-.134-.754l.52-.624a7.372 7.372 0 001.837-4.355 7.221 7.221 0 00-.29-2.489 5.644 5.644 0 00-3.116-3.424A5.771 5.771 0 006.753 2.87a5.7 5.7 0 00-1.19 2.047 7.22 7.22 0 00-.29 2.49 7.373 7.373 0 001.838 4.355l.518.622a.5.5 0 01-.134.753L3.5 15.444a5 5 0 00-2.5 4.33v2.231h13.54a5.981 5.981 0 01-1.19-2H3v-.23a3 3 0 011.5-2.6l3.995-2.308a2.5 2.5 0 00.67-3.766l-.521-.625a5.146 5.146 0 01-1.188-4.918 3.71 3.71 0 01.769-1.334 3.769 3.769 0 015.556 0c.346.386.608.84.768 1.334.157.562.22 1.146.187 1.728a5.379 5.379 0 01-1.373 3.188zm7.641-1.173a1 1 0 00-1 1v4.666h-1a3 3 0 103 3v-7.666a.999.999 0 00-1.003-1h.003zm-1 8.666a1 1 0 11-1-1h1v1z\'/>'
  }];
  var closestSize = findClosestGlyphAvailable(iconList, props.iconSize || 24);

  var titleTag = function titleTag(title, titleId) {
    return title ? "<title ".concat(titleId ? "id=\"".concat(titleId, "\"") : "", ">").concat(title, "</title>") : "";
  };

  var descTag = function descTag(desc, descId) {
    return desc ? "<desc ".concat(descId ? "id=\"".concat(descId, "\"") : "", ">").concat(desc, "</desc>") : "";
  };

  var autoMirror = (_props$autoMirror = props.autoMirror) !== null && _props$autoMirror !== void 0 ? _props$autoMirror : false;
  return /*#__PURE__*/React.createElement(Icon, Object.assign({}, props, {
    autoMirror: autoMirror,
    viewBox: "0 0 ".concat(closestSize.size, " ").concat(closestSize.size),
    dangerouslySetInnerHTML: {
      __html: "".concat(titleTag(props.title, props.titleId)).concat(descTag(props.desc, props.descId)).concat(closestSize.svgContent)
    }
  }));
}
/**
 * @deprecated The name Experimental__IconArtist is deprecated and will be archived soon. Use IconArtist instead.
 */

export function Experimental__IconArtist(props) {
  return /*#__PURE__*/React.createElement(IconArtist, props);
}