/**
 * Generated by `./scripts/prebuild/generate-icons.ts`.
 * Run `yarn generate-icons` to regenerate.
 */
import React from 'react';
import { findClosestGlyphAvailable, Icon } from "../../";
export function IconPlaybackSpeed2Point5x(props) {
  var _props$autoMirror;

  /* prettier-ignore */
  var iconList = [{
    'size': 16,
    'svgContent': '<path d=\'M2.42 2.83c0-.561.48-1.09 1.216-1.09s1.16.592 1.116 1.125a1.002 1.002 0 01-.548.836c-.1.056-.28.154-.466.255-.249.135-.508.276-.6.328h.002l-.026.012-.016.009-.067.034a5.665 5.665 0 00-.26.144 4.46 4.46 0 00-.718.521c-.512.46-1.056 1.2-1.056 2.253v.75h5.014v-1.5H2.72c.093-.143.208-.272.337-.387a3.17 3.17 0 01.703-.468 43.016 43.016 0 01.654-.356c.19-.103.388-.21.518-.282a2.5 2.5 0 001.315-2.022A2.568 2.568 0 003.636.24C2.156.24.92 1.359.92 2.83v.35h1.5v-.35zm12.889 7.7l-1.97 1.97 1.97 1.97-1.06 1.06-1.97-1.97-1.97 1.97-1.06-1.06 1.969-1.97-1.97-1.97 1.06-1.06 1.97 1.97 1.97-1.97 1.06 1.06zM10.82.5h3.749V2h-2.555l-.188.82a2.76 2.76 0 01.647-.075c1.515 0 2.763 1.214 2.763 2.734s-1.248 2.734-2.763 2.734a2.754 2.754 0 01-2.74-2.376l1.487-.197c.08.597.603 1.073 1.253 1.073.707 0 1.263-.562 1.263-1.234 0-.672-.556-1.234-1.263-1.234a1.27 1.27 0 00-1.028.516l-.01.014-.189.233-1.314-.639L10.819.5zM8.085 8.42a.956.956 0 100-1.913.956.956 0 000 1.913z\'/>'
  }, {
    'size': 24,
    'svgContent': '<path d=\'M3.398 4.555c0-1.02.87-1.945 2.146-1.945 1.302 0 2.066 1.054 1.984 2.017-.058.693-.411 1.183-.978 1.497-.164.09-.455.249-.753.41a82.975 82.975 0 00-.951.521L4.8 7.08l-.027.014-.105.054a8.875 8.875 0 00-.408.225 6.87 6.87 0 00-1.116.81c-.794.714-1.623 1.847-1.623 3.456v1h7.823v-2H3.74c.175-.378.44-.697.742-.969a5.318 5.318 0 011.174-.78c.07-.037.133-.069.183-.098.137-.078.491-.27.857-.469.306-.165.62-.336.823-.448 1.105-.613 1.883-1.67 2.002-3.078C9.696 2.728 8.08.61 5.544.61c-2.27 0-4.146 1.712-4.146 3.945v.56h2v-.56zM15.454.985h5.84v2h-4.247l-.412 1.794a4.26 4.26 0 011.304-.203c2.318 0 4.221 1.856 4.221 4.175 0 2.32-1.903 4.175-4.22 4.175-2.134 0-3.913-1.57-4.186-3.628l1.983-.263c.14 1.056 1.063 1.89 2.202 1.89 1.24 0 2.221-.986 2.221-2.174s-.98-2.175-2.22-2.175c-.747 0-1.403.359-1.806.908l-.013.018-.3.37-1.752-.852L15.454.985zm-3.715 11.689a.96.96 0 100-1.92.96.96 0 000 1.92zm10.303 3.923L19.5 19.14l2.543 2.543-1.414 1.414-2.543-2.543-2.543 2.543-1.414-1.415 2.543-2.542-2.543-2.543 1.414-1.415 2.543 2.543 2.543-2.543 1.414 1.415z\'/>'
  }];
  var closestSize = findClosestGlyphAvailable(iconList, props.iconSize || 24);

  var titleTag = function titleTag(title, titleId) {
    return title ? "<title ".concat(titleId ? "id=\"".concat(titleId, "\"") : "", ">").concat(title, "</title>") : "";
  };

  var descTag = function descTag(desc, descId) {
    return desc ? "<desc ".concat(descId ? "id=\"".concat(descId, "\"") : "", ">").concat(desc, "</desc>") : "";
  };

  var autoMirror = (_props$autoMirror = props.autoMirror) !== null && _props$autoMirror !== void 0 ? _props$autoMirror : false;
  return /*#__PURE__*/React.createElement(Icon, Object.assign({}, props, {
    autoMirror: autoMirror,
    viewBox: "0 0 ".concat(closestSize.size, " ").concat(closestSize.size),
    dangerouslySetInnerHTML: {
      __html: "".concat(titleTag(props.title, props.titleId)).concat(descTag(props.desc, props.descId)).concat(closestSize.svgContent)
    }
  }));
}
/**
 * @deprecated The name Experimental__IconPlaybackSpeed2Point5x is deprecated and will be archived soon. Use IconPlaybackSpeed2Point5x instead.
 */

export function Experimental__IconPlaybackSpeed2Point5x(props) {
  return /*#__PURE__*/React.createElement(IconPlaybackSpeed2Point5x, props);
}