"use strict";
let exports = {};
// DO NOT EDIT THIS FILE!
// This file was generated by UBI-generators.
// For support contact us on the #ubi slack channel.
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CarVoiceViewCarthingosEventFactory = exports.createCarVoiceViewCarthingosEventFactory = void 0;
var SPECIFICATION_ID = "car-voice-view-carthingos";
var APP = "music";
var SPECIFICATION_VERSION = "2.0.0";
var SPECIFICATION_MODE = "default";
var GENERATOR_VERSION = "10.0.2";
function createCarVoiceViewCarthingosEventFactory(options) {
    return new CarVoiceViewCarthingosEventFactory(options);
}
exports.createCarVoiceViewCarthingosEventFactory = createCarVoiceViewCarthingosEventFactory;
/**
 * Voice view on Car Thing
 */
var CarVoiceViewCarthingosEventFactory = /** @class */ (function () {
    function CarVoiceViewCarthingosEventFactory(options) {
        this._path = [{
                name: SPECIFICATION_ID
            }];
        if (options === null || options === void 0 ? void 0 : options.parentAbsoluteLocation) {
            this._parentAbsoluteLocation = options.parentAbsoluteLocation;
        }
    }
    /**
    * @returns A new instance of ListeningEventFactory
    */
    CarVoiceViewCarthingosEventFactory.prototype.listeningFactory = function () {
        return new CarVoiceViewCarthingosEventFactory.ListeningEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of ThinkingEventFactory
    */
    CarVoiceViewCarthingosEventFactory.prototype.thinkingFactory = function () {
        return new CarVoiceViewCarthingosEventFactory.ThinkingEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of BackButtonEventFactory
    */
    CarVoiceViewCarthingosEventFactory.prototype.backButtonFactory = function () {
        return new CarVoiceViewCarthingosEventFactory.BackButtonEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @param reason of the ErrorEventFactory
    * @returns A new instance of ErrorEventFactory
    */
    CarVoiceViewCarthingosEventFactory.prototype.errorFactory = function (data) {
        return new CarVoiceViewCarthingosEventFactory.ErrorEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation,
            data: data
        });
    };
    CarVoiceViewCarthingosEventFactory.prototype._getCurrentLocation = function () {
        return {
            pathNodes: this._path,
            specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
            specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
        };
    };
    CarVoiceViewCarthingosEventFactory.prototype.getAbsoluteLocation = function () {
        var _a;
        var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
        return {
            locations: __spreadArrays((parentLocations || []), [
                this._getCurrentLocation()
            ]),
        };
    };
    /**
     * Create interaction for swipe ui_hide action.
     */
    CarVoiceViewCarthingosEventFactory.prototype.swipeUiHide = function () {
        var data = {
            actionName: "ui_hide",
            actionVersion: 1,
            app: APP,
            generatorVersion: GENERATOR_VERSION,
            interactionType: "swipe",
            specificationMode: SPECIFICATION_MODE,
            specificationVersion: SPECIFICATION_VERSION,
            annotatorConfigurationVersion: '',
            annotatorVersion: '',
            location: this._getCurrentLocation(),
            parentAbsoluteLocation: this._parentAbsoluteLocation
        };
        return data;
    };
    /**
     * Create impression for CarVoiceViewCarthingosEventFactory.
     */
    CarVoiceViewCarthingosEventFactory.prototype.impression = function () {
        var data = {
            app: APP,
            generatorVersion: GENERATOR_VERSION,
            specificationVersion: SPECIFICATION_VERSION,
            specificationMode: SPECIFICATION_MODE,
            annotatorConfigurationVersion: '',
            annotatorVersion: '',
            location: this._getCurrentLocation(),
            parentAbsoluteLocation: this._parentAbsoluteLocation
        };
        return data;
    };
    return CarVoiceViewCarthingosEventFactory;
}());
exports.CarVoiceViewCarthingosEventFactory = CarVoiceViewCarthingosEventFactory;
(function (CarVoiceViewCarthingosEventFactory) {
    /**
     * Create ListeningEventFactory class with path
     * @param path to this node
     */
    var ListeningEventFactory = /** @class */ (function () {
        function ListeningEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "listening"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        ListeningEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        ListeningEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create impression for ListeningEventFactory.
         */
        ListeningEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return ListeningEventFactory;
    }());
    CarVoiceViewCarthingosEventFactory.ListeningEventFactory = ListeningEventFactory;
})(CarVoiceViewCarthingosEventFactory = exports.CarVoiceViewCarthingosEventFactory || (exports.CarVoiceViewCarthingosEventFactory = {}));
exports.CarVoiceViewCarthingosEventFactory = CarVoiceViewCarthingosEventFactory;
(function (CarVoiceViewCarthingosEventFactory) {
    /**
     * Create ThinkingEventFactory class with path
     * @param path to this node
     */
    var ThinkingEventFactory = /** @class */ (function () {
        function ThinkingEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "thinking"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        ThinkingEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        ThinkingEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create impression for ThinkingEventFactory.
         */
        ThinkingEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return ThinkingEventFactory;
    }());
    CarVoiceViewCarthingosEventFactory.ThinkingEventFactory = ThinkingEventFactory;
})(CarVoiceViewCarthingosEventFactory = exports.CarVoiceViewCarthingosEventFactory || (exports.CarVoiceViewCarthingosEventFactory = {}));
exports.CarVoiceViewCarthingosEventFactory = CarVoiceViewCarthingosEventFactory;
(function (CarVoiceViewCarthingosEventFactory) {
    /**
     * Create BackButtonEventFactory class with path
     * @param path to this node
     */
    var BackButtonEventFactory = /** @class */ (function () {
        function BackButtonEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "back_button"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        BackButtonEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        BackButtonEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for key_stroke ui_hide action.
         */
        BackButtonEventFactory.prototype.keyStrokeUiHide = function () {
            var data = {
                actionName: "ui_hide",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "key_stroke",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return BackButtonEventFactory;
    }());
    CarVoiceViewCarthingosEventFactory.BackButtonEventFactory = BackButtonEventFactory;
})(CarVoiceViewCarthingosEventFactory = exports.CarVoiceViewCarthingosEventFactory || (exports.CarVoiceViewCarthingosEventFactory = {}));
exports.CarVoiceViewCarthingosEventFactory = CarVoiceViewCarthingosEventFactory;
(function (CarVoiceViewCarthingosEventFactory) {
    /**
     * Create ErrorEventFactory class with path
     * @param path to this node
     */
    var ErrorEventFactory = /** @class */ (function () {
        function ErrorEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat(__assign(__assign({}, data), { name: "error" }));
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        ErrorEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        ErrorEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create interaction for hit retry action.
         */
        ErrorEventFactory.prototype.hitRetry = function () {
            var data = {
                actionName: "retry",
                actionVersion: 1,
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                interactionType: "hit",
                specificationMode: SPECIFICATION_MODE,
                specificationVersion: SPECIFICATION_VERSION,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        /**
         * Create impression for ErrorEventFactory.
         */
        ErrorEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return ErrorEventFactory;
    }());
    CarVoiceViewCarthingosEventFactory.ErrorEventFactory = ErrorEventFactory;
})(CarVoiceViewCarthingosEventFactory = exports.CarVoiceViewCarthingosEventFactory || (exports.CarVoiceViewCarthingosEventFactory = {}));
exports.CarVoiceViewCarthingosEventFactory = CarVoiceViewCarthingosEventFactory;

export { CarVoiceViewCarthingosEventFactory, createCarVoiceViewCarthingosEventFactory };