"use strict";
let exports = {};
// DO NOT EDIT THIS FILE!
// This file was generated by UBI-generators.
// For support contact us on the #ubi slack channel.
var __assign = (this && this.__assign) || function () {
    __assign = Object.assign || function(t) {
        for (var s, i = 1, n = arguments.length; i < n; i++) {
            s = arguments[i];
            for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
                t[p] = s[p];
        }
        return t;
    };
    return __assign.apply(this, arguments);
};
var __spreadArrays = (this && this.__spreadArrays) || function () {
    for (var s = 0, i = 0, il = arguments.length; i < il; i++) s += arguments[i].length;
    for (var r = Array(s), k = 0, i = 0; i < il; i++)
        for (var a = arguments[i], j = 0, jl = a.length; j < jl; j++, k++)
            r[k] = a[j];
    return r;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CarOnboardingLearnTactileCarthingosEventFactory = exports.createCarOnboardingLearnTactileCarthingosEventFactory = void 0;
var SPECIFICATION_ID = "car-onboarding-learn-tactile-carthingos";
var APP = "music";
var SPECIFICATION_VERSION = "1.0.0";
var SPECIFICATION_MODE = "default";
var GENERATOR_VERSION = "10.0.2";
function createCarOnboardingLearnTactileCarthingosEventFactory(options) {
    return new CarOnboardingLearnTactileCarthingosEventFactory(options);
}
exports.createCarOnboardingLearnTactileCarthingosEventFactory = createCarOnboardingLearnTactileCarthingosEventFactory;
/**
 *
 */
var CarOnboardingLearnTactileCarthingosEventFactory = /** @class */ (function () {
    function CarOnboardingLearnTactileCarthingosEventFactory(options) {
        this._path = [{
                name: SPECIFICATION_ID
            }];
        if (options === null || options === void 0 ? void 0 : options.parentAbsoluteLocation) {
            this._parentAbsoluteLocation = options.parentAbsoluteLocation;
        }
    }
    /**
    * @returns A new instance of LastStepContainerEventFactory
    */
    CarOnboardingLearnTactileCarthingosEventFactory.prototype.lastStepContainerFactory = function () {
        return new CarOnboardingLearnTactileCarthingosEventFactory.LastStepContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of ContentShelfContainerEventFactory
    */
    CarOnboardingLearnTactileCarthingosEventFactory.prototype.contentShelfContainerFactory = function () {
        return new CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of TrackViewContainerEventFactory
    */
    CarOnboardingLearnTactileCarthingosEventFactory.prototype.trackViewContainerFactory = function () {
        return new CarOnboardingLearnTactileCarthingosEventFactory.TrackViewContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @returns A new instance of NpvContainerEventFactory
    */
    CarOnboardingLearnTactileCarthingosEventFactory.prototype.npvContainerFactory = function () {
        return new CarOnboardingLearnTactileCarthingosEventFactory.NpvContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation
        });
    };
    /**
    * @param reason of the NoInteractionContainerEventFactory
    * @returns A new instance of NoInteractionContainerEventFactory
    */
    CarOnboardingLearnTactileCarthingosEventFactory.prototype.noInteractionContainerFactory = function (data) {
        return new CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory({
            path: this._path,
            parentAbsoluteLocation: this._parentAbsoluteLocation,
            data: data
        });
    };
    CarOnboardingLearnTactileCarthingosEventFactory.prototype._getCurrentLocation = function () {
        return {
            pathNodes: this._path,
            specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
            specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
        };
    };
    CarOnboardingLearnTactileCarthingosEventFactory.prototype.getAbsoluteLocation = function () {
        var _a;
        var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
        return {
            locations: __spreadArrays((parentLocations || []), [
                this._getCurrentLocation()
            ]),
        };
    };
    return CarOnboardingLearnTactileCarthingosEventFactory;
}());
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    /**
     * Create LastStepContainerEventFactory class with path
     * @param path to this node
     */
    var LastStepContainerEventFactory = /** @class */ (function () {
        function LastStepContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "last_step_container"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of SkipButtonEventFactory
        */
        LastStepContainerEventFactory.prototype.skipButtonFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.LastStepContainerEventFactory.SkipButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        LastStepContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        LastStepContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create impression for LastStepContainerEventFactory.
         */
        LastStepContainerEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return LastStepContainerEventFactory;
    }());
    CarOnboardingLearnTactileCarthingosEventFactory.LastStepContainerEventFactory = LastStepContainerEventFactory;
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    /**
     * Create ContentShelfContainerEventFactory class with path
     * @param path to this node
     */
    var ContentShelfContainerEventFactory = /** @class */ (function () {
        function ContentShelfContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "content_shelf_container"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of RotateDialIndicatorEventFactory
        */
        ContentShelfContainerEventFactory.prototype.rotateDialIndicatorFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory.RotateDialIndicatorEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of PressDialIndicatorEventFactory
        */
        ContentShelfContainerEventFactory.prototype.pressDialIndicatorFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory.PressDialIndicatorEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of BackButtonIndicatorEventFactory
        */
        ContentShelfContainerEventFactory.prototype.backButtonIndicatorFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory.BackButtonIndicatorEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        ContentShelfContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        ContentShelfContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        return ContentShelfContainerEventFactory;
    }());
    CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory = ContentShelfContainerEventFactory;
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    /**
     * Create TrackViewContainerEventFactory class with path
     * @param path to this node
     */
    var TrackViewContainerEventFactory = /** @class */ (function () {
        function TrackViewContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "track_view_container"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of PressDialIndicatorEventFactory
        */
        TrackViewContainerEventFactory.prototype.pressDialIndicatorFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.TrackViewContainerEventFactory.PressDialIndicatorEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of BackButtonIndicatorEventFactory
        */
        TrackViewContainerEventFactory.prototype.backButtonIndicatorFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.TrackViewContainerEventFactory.BackButtonIndicatorEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        TrackViewContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        TrackViewContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        return TrackViewContainerEventFactory;
    }());
    CarOnboardingLearnTactileCarthingosEventFactory.TrackViewContainerEventFactory = TrackViewContainerEventFactory;
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    /**
     * Create NpvContainerEventFactory class with path
     * @param path to this node
     */
    var NpvContainerEventFactory = /** @class */ (function () {
        function NpvContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat({
                name: "npv_container"
            });
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of PressDialIndicatorEventFactory
        */
        NpvContainerEventFactory.prototype.pressDialIndicatorFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.NpvContainerEventFactory.PressDialIndicatorEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of BackButtonIndicatorEventFactory
        */
        NpvContainerEventFactory.prototype.backButtonIndicatorFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.NpvContainerEventFactory.BackButtonIndicatorEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        NpvContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        NpvContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        return NpvContainerEventFactory;
    }());
    CarOnboardingLearnTactileCarthingosEventFactory.NpvContainerEventFactory = NpvContainerEventFactory;
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    /**
     * Create NoInteractionContainerEventFactory class with path
     * @param path to this node
     */
    var NoInteractionContainerEventFactory = /** @class */ (function () {
        function NoInteractionContainerEventFactory(_a) {
            var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
            this._path = path.concat(__assign(__assign({}, data), { name: "no_interaction_container" }));
            if (parentAbsoluteLocation) {
                this._parentAbsoluteLocation = parentAbsoluteLocation;
            }
        }
        /**
        * @returns A new instance of ContinueButtonEventFactory
        */
        NoInteractionContainerEventFactory.prototype.continueButtonFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory.ContinueButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of EndButtonEventFactory
        */
        NoInteractionContainerEventFactory.prototype.endButtonFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory.EndButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        /**
        * @returns A new instance of BackButtonEventFactory
        */
        NoInteractionContainerEventFactory.prototype.backButtonFactory = function () {
            return new CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory.BackButtonEventFactory({
                path: this._path,
                parentAbsoluteLocation: this._parentAbsoluteLocation
            });
        };
        NoInteractionContainerEventFactory.prototype._getCurrentLocation = function () {
            return {
                pathNodes: this._path,
                specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
            };
        };
        NoInteractionContainerEventFactory.prototype.getAbsoluteLocation = function () {
            var _a;
            var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
            return {
                locations: __spreadArrays((parentLocations || []), [
                    this._getCurrentLocation()
                ]),
            };
        };
        /**
         * Create impression for NoInteractionContainerEventFactory.
         */
        NoInteractionContainerEventFactory.prototype.impression = function () {
            var data = {
                app: APP,
                generatorVersion: GENERATOR_VERSION,
                specificationVersion: SPECIFICATION_VERSION,
                specificationMode: SPECIFICATION_MODE,
                annotatorConfigurationVersion: '',
                annotatorVersion: '',
                location: this._getCurrentLocation(),
                parentAbsoluteLocation: this._parentAbsoluteLocation
            };
            return data;
        };
        return NoInteractionContainerEventFactory;
    }());
    CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory = NoInteractionContainerEventFactory;
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var LastStepContainerEventFactory;
    (function (LastStepContainerEventFactory) {
        /**
         * Create SkipButtonEventFactory class with path
         * @param path to this node
         */
        var SkipButtonEventFactory = /** @class */ (function () {
            function SkipButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "skip_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            SkipButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            SkipButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_navigate action.
           * @param destination the destination field
             */
            SkipButtonEventFactory.prototype.hitUiNavigate = function (_a) {
                var destination = _a.destination;
                var data = {
                    actionParameterNames: ['destination'],
                    actionParameterValues: [destination.toString()],
                    actionName: "ui_navigate",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return SkipButtonEventFactory;
        }());
        LastStepContainerEventFactory.SkipButtonEventFactory = SkipButtonEventFactory;
    })(LastStepContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.LastStepContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.LastStepContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var ContentShelfContainerEventFactory;
    (function (ContentShelfContainerEventFactory) {
        /**
         * Create RotateDialIndicatorEventFactory class with path
         * @param path to this node
         */
        var RotateDialIndicatorEventFactory = /** @class */ (function () {
            function RotateDialIndicatorEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "rotate_dial_indicator"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            RotateDialIndicatorEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            RotateDialIndicatorEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create impression for RotateDialIndicatorEventFactory.
             */
            RotateDialIndicatorEventFactory.prototype.impression = function () {
                var data = {
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    specificationVersion: SPECIFICATION_VERSION,
                    specificationMode: SPECIFICATION_MODE,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return RotateDialIndicatorEventFactory;
        }());
        ContentShelfContainerEventFactory.RotateDialIndicatorEventFactory = RotateDialIndicatorEventFactory;
    })(ContentShelfContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var ContentShelfContainerEventFactory;
    (function (ContentShelfContainerEventFactory) {
        /**
         * Create PressDialIndicatorEventFactory class with path
         * @param path to this node
         */
        var PressDialIndicatorEventFactory = /** @class */ (function () {
            function PressDialIndicatorEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "press_dial_indicator"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            PressDialIndicatorEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            PressDialIndicatorEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create impression for PressDialIndicatorEventFactory.
             */
            PressDialIndicatorEventFactory.prototype.impression = function () {
                var data = {
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    specificationVersion: SPECIFICATION_VERSION,
                    specificationMode: SPECIFICATION_MODE,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return PressDialIndicatorEventFactory;
        }());
        ContentShelfContainerEventFactory.PressDialIndicatorEventFactory = PressDialIndicatorEventFactory;
    })(ContentShelfContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var ContentShelfContainerEventFactory;
    (function (ContentShelfContainerEventFactory) {
        /**
         * Create BackButtonIndicatorEventFactory class with path
         * @param path to this node
         */
        var BackButtonIndicatorEventFactory = /** @class */ (function () {
            function BackButtonIndicatorEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "back_button_indicator"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            BackButtonIndicatorEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            BackButtonIndicatorEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create impression for BackButtonIndicatorEventFactory.
             */
            BackButtonIndicatorEventFactory.prototype.impression = function () {
                var data = {
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    specificationVersion: SPECIFICATION_VERSION,
                    specificationMode: SPECIFICATION_MODE,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return BackButtonIndicatorEventFactory;
        }());
        ContentShelfContainerEventFactory.BackButtonIndicatorEventFactory = BackButtonIndicatorEventFactory;
    })(ContentShelfContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.ContentShelfContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var TrackViewContainerEventFactory;
    (function (TrackViewContainerEventFactory) {
        /**
         * Create PressDialIndicatorEventFactory class with path
         * @param path to this node
         */
        var PressDialIndicatorEventFactory = /** @class */ (function () {
            function PressDialIndicatorEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "press_dial_indicator"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            PressDialIndicatorEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            PressDialIndicatorEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create impression for PressDialIndicatorEventFactory.
             */
            PressDialIndicatorEventFactory.prototype.impression = function () {
                var data = {
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    specificationVersion: SPECIFICATION_VERSION,
                    specificationMode: SPECIFICATION_MODE,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return PressDialIndicatorEventFactory;
        }());
        TrackViewContainerEventFactory.PressDialIndicatorEventFactory = PressDialIndicatorEventFactory;
    })(TrackViewContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.TrackViewContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.TrackViewContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var TrackViewContainerEventFactory;
    (function (TrackViewContainerEventFactory) {
        /**
         * Create BackButtonIndicatorEventFactory class with path
         * @param path to this node
         */
        var BackButtonIndicatorEventFactory = /** @class */ (function () {
            function BackButtonIndicatorEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "back_button_indicator"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            BackButtonIndicatorEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            BackButtonIndicatorEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create impression for BackButtonIndicatorEventFactory.
             */
            BackButtonIndicatorEventFactory.prototype.impression = function () {
                var data = {
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    specificationVersion: SPECIFICATION_VERSION,
                    specificationMode: SPECIFICATION_MODE,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return BackButtonIndicatorEventFactory;
        }());
        TrackViewContainerEventFactory.BackButtonIndicatorEventFactory = BackButtonIndicatorEventFactory;
    })(TrackViewContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.TrackViewContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.TrackViewContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var NpvContainerEventFactory;
    (function (NpvContainerEventFactory) {
        /**
         * Create PressDialIndicatorEventFactory class with path
         * @param path to this node
         */
        var PressDialIndicatorEventFactory = /** @class */ (function () {
            function PressDialIndicatorEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "press_dial_indicator"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            PressDialIndicatorEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            PressDialIndicatorEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create impression for PressDialIndicatorEventFactory.
             */
            PressDialIndicatorEventFactory.prototype.impression = function () {
                var data = {
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    specificationVersion: SPECIFICATION_VERSION,
                    specificationMode: SPECIFICATION_MODE,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return PressDialIndicatorEventFactory;
        }());
        NpvContainerEventFactory.PressDialIndicatorEventFactory = PressDialIndicatorEventFactory;
    })(NpvContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.NpvContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.NpvContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var NpvContainerEventFactory;
    (function (NpvContainerEventFactory) {
        /**
         * Create BackButtonIndicatorEventFactory class with path
         * @param path to this node
         */
        var BackButtonIndicatorEventFactory = /** @class */ (function () {
            function BackButtonIndicatorEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "back_button_indicator"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            BackButtonIndicatorEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            BackButtonIndicatorEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create impression for BackButtonIndicatorEventFactory.
             */
            BackButtonIndicatorEventFactory.prototype.impression = function () {
                var data = {
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    specificationVersion: SPECIFICATION_VERSION,
                    specificationMode: SPECIFICATION_MODE,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return BackButtonIndicatorEventFactory;
        }());
        NpvContainerEventFactory.BackButtonIndicatorEventFactory = BackButtonIndicatorEventFactory;
    })(NpvContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.NpvContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.NpvContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var NoInteractionContainerEventFactory;
    (function (NoInteractionContainerEventFactory) {
        /**
         * Create ContinueButtonEventFactory class with path
         * @param path to this node
         */
        var ContinueButtonEventFactory = /** @class */ (function () {
            function ContinueButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "continue_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            ContinueButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            ContinueButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_hide action.
             */
            ContinueButtonEventFactory.prototype.hitUiHide = function () {
                var data = {
                    actionName: "ui_hide",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            /**
             * Create interaction for key_stroke ui_hide action.
             */
            ContinueButtonEventFactory.prototype.keyStrokeUiHide = function () {
                var data = {
                    actionName: "ui_hide",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "key_stroke",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return ContinueButtonEventFactory;
        }());
        NoInteractionContainerEventFactory.ContinueButtonEventFactory = ContinueButtonEventFactory;
    })(NoInteractionContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var NoInteractionContainerEventFactory;
    (function (NoInteractionContainerEventFactory) {
        /**
         * Create EndButtonEventFactory class with path
         * @param path to this node
         */
        var EndButtonEventFactory = /** @class */ (function () {
            function EndButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "end_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            EndButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            EndButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for hit ui_navigate action.
           * @param destination the destination field
             */
            EndButtonEventFactory.prototype.hitUiNavigate = function (_a) {
                var destination = _a.destination;
                var data = {
                    actionParameterNames: ['destination'],
                    actionParameterValues: [destination.toString()],
                    actionName: "ui_navigate",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "hit",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            /**
             * Create interaction for key_stroke ui_navigate action.
           * @param destination the destination field
             */
            EndButtonEventFactory.prototype.keyStrokeUiNavigate = function (_a) {
                var destination = _a.destination;
                var data = {
                    actionParameterNames: ['destination'],
                    actionParameterValues: [destination.toString()],
                    actionName: "ui_navigate",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "key_stroke",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return EndButtonEventFactory;
        }());
        NoInteractionContainerEventFactory.EndButtonEventFactory = EndButtonEventFactory;
    })(NoInteractionContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;
(function (CarOnboardingLearnTactileCarthingosEventFactory) {
    var NoInteractionContainerEventFactory;
    (function (NoInteractionContainerEventFactory) {
        /**
         * Create BackButtonEventFactory class with path
         * @param path to this node
         */
        var BackButtonEventFactory = /** @class */ (function () {
            function BackButtonEventFactory(_a) {
                var path = _a.path, parentAbsoluteLocation = _a.parentAbsoluteLocation, data = _a.data;
                this._path = path.concat({
                    name: "back_button"
                });
                if (parentAbsoluteLocation) {
                    this._parentAbsoluteLocation = parentAbsoluteLocation;
                }
            }
            BackButtonEventFactory.prototype._getCurrentLocation = function () {
                return {
                    pathNodes: this._path,
                    specMode: __spreadArrays([SPECIFICATION_MODE], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; })),
                    specVersion: __spreadArrays([SPECIFICATION_VERSION], __spreadArrays(Array(this._path.length - 1)).map(function () { return ''; }))
                };
            };
            BackButtonEventFactory.prototype.getAbsoluteLocation = function () {
                var _a;
                var parentLocations = (_a = this._parentAbsoluteLocation) === null || _a === void 0 ? void 0 : _a.locations;
                return {
                    locations: __spreadArrays((parentLocations || []), [
                        this._getCurrentLocation()
                    ]),
                };
            };
            /**
             * Create interaction for key_stroke ui_hide action.
             */
            BackButtonEventFactory.prototype.keyStrokeUiHide = function () {
                var data = {
                    actionName: "ui_hide",
                    actionVersion: 1,
                    app: APP,
                    generatorVersion: GENERATOR_VERSION,
                    interactionType: "key_stroke",
                    specificationMode: SPECIFICATION_MODE,
                    specificationVersion: SPECIFICATION_VERSION,
                    annotatorConfigurationVersion: '',
                    annotatorVersion: '',
                    location: this._getCurrentLocation(),
                    parentAbsoluteLocation: this._parentAbsoluteLocation
                };
                return data;
            };
            return BackButtonEventFactory;
        }());
        NoInteractionContainerEventFactory.BackButtonEventFactory = BackButtonEventFactory;
    })(NoInteractionContainerEventFactory = CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory || (CarOnboardingLearnTactileCarthingosEventFactory.NoInteractionContainerEventFactory = {}));
})(CarOnboardingLearnTactileCarthingosEventFactory = exports.CarOnboardingLearnTactileCarthingosEventFactory || (exports.CarOnboardingLearnTactileCarthingosEventFactory = {}));
exports.CarOnboardingLearnTactileCarthingosEventFactory = CarOnboardingLearnTactileCarthingosEventFactory;

export { CarOnboardingLearnTactileCarthingosEventFactory, createCarOnboardingLearnTactileCarthingosEventFactory };