name: build and release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags
      - 'v*.*.*-*' # Trigger for pre-release tags
  workflow_dispatch: # Allows manual triggering

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Build ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            DeskThingServer

      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd DeskThingServer
          npm ci

      - name: Build/release Electron app
        uses: paneron/action-electron-builder@v1.8.1
        with:
          github_token: ${{ secrets.github_token }}
          package_manager: npm
          package_root: ${{ github.workspace }}/DeskThingServer
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Get Current Release
        id: get_current_release
        uses: joutvhu/get-release@v1
        with:
          latest: true
          pattern: '^v.*'
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries to release
        uses: jaywcjlove/github-action-upload-assets@main
        with:
          asset-path: '["${{ github.workspace }}/DeskThingServer/dist/deskthing-*"]'
          tag: ${{ steps.get_current_release.outputs.tag_name }}
