name: Build/release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags
      - 'v*.*.*-*' # Trigger for pre-release tags
  workflow_dispatch: # Allows manual triggering

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    name: Build ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            DeskThingServer

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: /DeskThingServer/package-lock.json
      - run: npm ci
      - run: npm test

      - name: Build/release Electron app
        uses: paneron/action-electron-builder@v1.8.1
        with:
          github_token: ${{ secrets.github_token }}
          package_manager: npm
          package_root: ${{ github.workspace }}/DeskThingServer
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
