name: Build/release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags
      - 'v*.*.*-*' # Trigger for pre-release tags
  workflow_dispatch: # Allows manual triggering

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    name: Build ${{ matrix.os }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            DeskThingServer

      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd DeskThingServer
          npm ci

      - name: Build/release Electron app
        uses: paneron/action-electron-builder@v1.8.1
        with:
          github_token: ${{ secrets.github_token }}
          package_manager: npm
          package_root: ${{ github.workspace }}/DeskThingServer
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.github_token }}
          file: ${{ startsWith(github.ref, 'refs/tags/v') }}
          asset_name: DeskThing-${{ steps.get_version.outputs.VERSION }}-${{ matrix.os }}
          tag: ${{ steps.get_version.outputs.VERSION }}
