name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers on version tags
      - 'v*.*.*-*' # Trigger for pre-release tags
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest] # Matrix for multiple OS builds

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd ./DeskThingServer
          npm ci

      - name: Run type check
        run: |
          cd ./DeskThingServer
          npm run typecheck

      - name: Install snapcraft on Linux
        if: runner.os == 'Linux'
        run: |
          sudo snap install snapcraft --classic

      - name: Build the project
        run: |
          cd ./DeskThingServer
          npm run build

      - name: Build application for Windows
        if: runner.os == 'Windows'
        run: |
          cd ./DeskThingServer
          npm run build:win

      - name: Build application for macOS
        if: runner.os == 'macOS'
        run: |
          cd ./DeskThingServer
          npm run build:mac

      - name: Build application for Linux
        if: runner.os == 'Linux'
        run: |
          cd ./DeskThingServer
          npm run build:linux

      - name: Upload artifact for Windows
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: DeskThing-windows-latest # Artifact name for Windows
          path: |
            ./DeskThingServer/dist/*
            !./DeskThingServer/dist/**/*.map

      - name: Upload artifact for macOS
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: DeskThing-macos-latest # Artifact name for macOS
          path: |
            ./DeskThingServer/dist/*
            !./DeskThingServer/dist/**/*.map

      - name: Upload artifact for Linux
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: DeskThing-ubuntu-latest # Artifact name for Linux
          path: |
            ./DeskThingServer/dist/*
            !./DeskThingServer/dist/**/*.map

  release:
    needs: build # Runs after build job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: DeskThing-ubuntu-latest
          path: ./dist/ubuntu
      - uses: actions/download-artifact@v3
        with:
          name: DeskThing-macos-latest
          path: ./dist/macos
      - uses: actions/download-artifact@v3
        with:
          name: DeskThing-windows-latest
          path: ./dist/windows

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/ubuntu/*
            ./dist/macos/*
            ./dist/windows/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
